### ISSUE TITLE
Vagrant build does not work

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-android#360]
I partially fixed this in #359 to fix Sphinx part of the build, but there are still numerous errors - for example:

```
==> default:    at java.lang.reflect.Method.invoke(Method.java:606)
==> default:    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
==> default:    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
==> default:    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
==> default: FAILURE:
==> default: Build failed with an exception.
==> default: * Where:
==> default: Script '/vagrant/release_android_library.gradle' line: 31
==> default: * What went wrong:
==> default: A problem occurred evaluating script.
==> default: >
==> default: The SDK directory '/root/android-sdk-linux' does not exist.
==> default: * Try:
==> default: Run with
==> default: --stacktrace
==> default:  option to get the stack trace. Run with
==> default: --info
==> default:  or
==> default: --debug
==> default:  option to get more log output.
==> default: BUILD FAILED
```

**Comment by ne0fhyk** [comment]
@hamishwillee the issue was moved to jira for better tracking.
