### ISSUE TITLE
Exception thrown when stopping the saving videos locally

### ISSUE THREAD

**Issue by phmagic** [dronekit/dronekit-android#432]
08-24 15:33:09.365 6700-7312/com.o3dr.solo.android.dev E/AbstractIpConnection: Error occurred while reading from the connection.
                                                                               java.net.SocketException: Socket closed
                                                                                   at java.net.PlainDatagramSocketImpl.receive0(Native Method)
                                                                                   at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:147)
                                                                                   at java.net.DatagramSocket.receive(DatagramSocket.java:811)
                                                                                   at com.o3dr.android.client.utils.connection.UdpConnection.read(UdpConnection.java:68)
                                                                                   at com.o3dr.android.client.utils.connection.AbstractIpConnection$1.run(AbstractIpConnection.java:81)
                                                                                   at java.lang.Thread.run(Thread.java:761)

**Comment by ne0fhyk** [comment]
@phmagic Seems not to be related to video saving. This issue should be fixed by pr #433.
